name: 部署前端到 GitHub Pages

on:
  push:
    branches: [ master ] # 当你向 main 分支推送代码时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: 安装并打包前端
        run: |
          cd frontend
          npm install
          npm run build

      - name: 发布到 GitHub Pages 分支
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist # 告诉它打包后的文件在子文件夹里
          branch: gh-pages # 自动部署到这个分支